### ISSUE TITLE
How did you set different penalties in parameters.py?

### ISSUE THREAD

**Issue by yixin94** [BrightFeather/deeprm_conv#1]
Hi!
How did you set different penalties in parameters.py? In parameters.py, `self.delay_penalty = -1, self.hold_penalty = -1, self.dismiss_penalty = -1`.
Thanks!

**Comment by BrightFeather** [comment]
I ran some experiments by setting different values for those three parameters and found that setting self.delay_penalty = -1, self.hold_penalty = -2, self.dismiss_penalty = -1 works better.

**Comment by yixin94** [comment]
I see. Thank you! ^_^
